ktor:
  application:
    modules:
      - tech.weinmann.raas.ApplicationKt.module
  deployment:
    port: 8080
database:
  url: "jdbc:h2:mem:fake;DB_CLOSE_DELAY=-1"
  user: "root"
  driver: "org.h2.Driver"
  password: ""
